id: P010788
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:33.304559
source_metadata:
  id: bdr:W1KG1791
  title: མི་མིན་དངུལ་རྫོང
  author: ''
  volumes:
    028e1e5dec0d48d980346263eb0a5dcf:
      image_group_id: I1KG1848
      title: ''
      volume_number: 1
      total_pages: 488
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
